<a href="https://colab.research.google.com/github/kwangminK/Crowling/blob/main/mininet_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
from torch import nn
from torch import optim

In [ ]:
x=torch.randn(100,3)
layer = nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.5727,  0.2223, -0.1237],
        [ 0.5685,  0.0817, -0.3573],
        [-0.0531,  0.3884, -0.0801],
        [ 0.1900,  0.4881, -0.4303],
        [ 0.3568,  0.0615, -0.5364]], requires_grad=True)
Parameter containing:
tensor([-0.5526,  0.4363, -0.5140, -0.1469,  0.5566], requires_grad=True)


In [ ]:
x=torch.randn(2,5)
layer=nn.ReLU() # 음수는 0, 양수는 그대로 통과
print(layer(x))

tensor([[0.2800, 0.0000, 1.1287, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.3106, 0.1386]])


In [ ]:
x= torch.randn(3,7)
drop = nn.Dropout(p=0.3) # p는 죽일 확률
# 죽이면 0으로 통과된다.
print(drop(x))

tensor([[-2.3303, -0.0000,  0.8410, -0.0000,  2.0958, -0.6162,  0.5172],
        [ 2.7774, -3.8665,  0.8504,  0.4953,  0.0000,  1.2857, -0.0000],
        [-1.6386, -0.0000,  0.0000,  1.0260,  0.0000,  0.5531, -1.0829]])


In [ ]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.Dropout(p=0.3))
                                      
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode
# test에서는 weight에 살릴 확률을 곱하여 드롭아웃하지 않고, 통과한다.

tensor([[-0.0000, -0.0000, -0.7226, -0.0000, -0.0000,  0.0000,  0.0000],
        [-0.2532, -0.9571,  0.1233, -0.0000, -0.0000,  0.9946,  0.0000],
        [ 0.0000, -1.2533,  0.1459,  0.1525, -0.0000,  0.0000,  0.0977]],
       grad_fn=<MulBackward0>)
tensor([[-0.2863, -1.2834, -0.5058, -0.3712, -0.9334,  1.0518,  0.3817],
        [-0.1772, -0.6700,  0.0863, -0.0788, -0.5712,  0.6962,  0.4156],
        [ 0.3440, -0.8773,  0.1021,  0.1067, -0.4144,  0.8338,  0.0684]],
       grad_fn=<AddmmBackward0>)


In [ ]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # 채채 #얘는 채또는 개채를 원함, 개x3 => 개x5
# nn.Conv2d(3,5) # 채채 # 근데 얘는 채행렬 또는 개채행렬을 원함, 개x3x행x렬 => 개x5x행x렬

torch.Size([32, 2, 3, 3])

In [ ]:
layer = nn.Conv2d(3,5,3) # weight가 3x3x3짜리 5개 존재
print(layer(torch.randn(32,3,5,5)).shape)
print(layer.weight.shape) 
# >>>torch.Size([5개의 커널, 3개의 전단계의 채널, 3, 3]) 3x3짜리 커널

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [ ]:
conv1 = nn.Conv2d(1,8,6, stride=2)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)
print(conv1.weight.shape)

conv2 = nn.Conv2d(8,16,3, padding=1) # padding=1 커널 사이즈 유지
print(conv2(conv1(x)).shape)

MaxPool = nn.MaxPool2d(kernel_size=2, stride=(2,2))
print(MaxPool(conv2(conv1(x))).shape)

torch.Size([32, 8, 12, 12])
torch.Size([8, 1, 6, 6])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [ ]:
maxpool = nn.MaxPool2d(2)
x= torch.randn(1,6,6)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[ 1.0661, -0.8072, -2.3912, -0.3228,  0.2031, -0.4252],
         [ 0.2895, -0.4701, -0.6140, -2.0668,  0.0909,  0.3200],
         [ 0.1219,  1.4791, -2.9433, -2.8630, -0.9424, -0.7350],
         [-2.0227, -1.1433,  1.2258,  0.5360, -1.4818, -0.1243],
         [ 0.8882, -0.2548, -1.1313, -1.3912, -0.2206,  0.2007],
         [-1.4542,  0.3301,  3.0546,  0.1853, -1.6771,  0.7605]]])
tensor([[[ 1.0661, -0.3228,  0.3200],
         [ 1.4791,  1.2258, -0.1243],
         [ 0.8882,  3.0546,  0.7605]]])
torch.Size([32, 3, 3, 3])


In [ ]:
avgpool = nn.AvgPool2d(2)
x= torch.randn(1,6,6)
print(x)
print(avgpool(x))
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[-0.8174,  0.4074, -0.7465,  0.2245,  1.6700, -1.1934],
         [-0.2566, -1.0873,  0.2743,  0.0334,  0.1821,  0.9852],
         [ 1.7390, -1.5211,  0.6394, -0.2092,  1.6672, -0.1714],
         [-2.0078,  1.4508,  1.4841, -0.2647, -1.4111,  0.0327],
         [ 0.9907, -0.9130,  0.3100,  0.0954, -1.1122,  0.2181],
         [-1.7583, -0.0841, -0.1771, -0.2324,  0.3786,  0.5118]]])
tensor([[[-0.4385, -0.0536,  0.4110],
         [-0.0848,  0.4124,  0.0293],
         [-0.4412, -0.0010, -0.0009]]])
torch.Size([32, 3, 3, 3])


In [ ]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)

    def forward(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool(x)
        x = torch.flatten(x, start_dim=1) #이것과 밑에것을 주석처리하고 실행시키면 linear에 들어가는것을 알수있음
        x = self.fc(x)
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 10])


## .parameters() vs .modules() vs. children() 그리고 isinstance의 활용

In [ ]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x
        
model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [ ]:
model.parameters()

<generator object Module.parameters at 0x7fe1ed188cf0>

In [ ]:
list(model.parameters())[0]
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[-0.4239, -0.3028],
        [-0.0127, -0.0641],
        [ 0.2500, -0.4777]], requires_grad=True)

In [ ]:
# for transfer learning
model = MLP()

for p in model.parameters(): # 전체 freeze 학습하지않겠다.
    p.requires_grad = False 
model.fc_out = nn.Linear(4,10) # 이렇게 하는 순간 requires_grad = True

params = [p for p in model.parameters()]
print(params)


[Parameter containing:
tensor([[-0.1397, -0.0223],
        [-0.5707, -0.6512],
        [ 0.5496, -0.5940]]), Parameter containing:
tensor([ 0.4537, -0.0643,  0.3841]), Parameter containing:
tensor([[-0.3149,  0.3908, -0.2068],
        [-0.1922, -0.5634,  0.2981],
        [-0.1644,  0.3122, -0.1824],
        [-0.1548, -0.1457, -0.3756]]), Parameter containing:
tensor([ 0.5513, -0.3423, -0.2688, -0.5746]), Parameter containing:
tensor([[-0.0990,  0.2766, -0.4011,  0.3329],
        [ 0.1677,  0.2721,  0.2828, -0.0207],
        [ 0.1096, -0.3946,  0.0477,  0.2217],
        [ 0.1411,  0.4644,  0.3425,  0.2077],
        [ 0.2591, -0.2632, -0.2729,  0.3236],
        [-0.1293,  0.3663, -0.4023,  0.3493],
        [ 0.1964,  0.3094, -0.3887,  0.4245],
        [-0.3033,  0.3585,  0.1290,  0.3366],
        [ 0.3829,  0.0898,  0.0013, -0.1901],
        [-0.3746, -0.2144, -0.3620, -0.0820]], requires_grad=True), Parameter containing:
tensor([-0.0308,  0.3636, -0.4807, -0.1876, -0.0129,  0.4031,  0.3

In [ ]:
list(model.named_parameters())
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...]

[('fc1.0.weight', Parameter containing:
  tensor([[-0.1397, -0.0223],
          [-0.5707, -0.6512],
          [ 0.5496, -0.5940]])), ('fc1.0.bias', Parameter containing:
  tensor([ 0.4537, -0.0643,  0.3841])), ('fc2.0.weight', Parameter containing:
  tensor([[-0.3149,  0.3908, -0.2068],
          [-0.1922, -0.5634,  0.2981],
          [-0.1644,  0.3122, -0.1824],
          [-0.1548, -0.1457, -0.3756]])), ('fc2.0.bias', Parameter containing:
  tensor([ 0.5513, -0.3423, -0.2688, -0.5746])), ('fc_out.weight',
  Parameter containing:
  tensor([[-0.0990,  0.2766, -0.4011,  0.3329],
          [ 0.1677,  0.2721,  0.2828, -0.0207],
          [ 0.1096, -0.3946,  0.0477,  0.2217],
          [ 0.1411,  0.4644,  0.3425,  0.2077],
          [ 0.2591, -0.2632, -0.2729,  0.3236],
          [-0.1293,  0.3663, -0.4023,  0.3493],
          [ 0.1964,  0.3094, -0.3887,  0.4245],
          [-0.3033,  0.3585,  0.1290,  0.3366],
          [ 0.3829,  0.0898,  0.0013, -0.1901],
          [-0.3746, -0.2144, -0.

In [ ]:
for name, p in model.named_parameters():
    print(name)

fc1.0.weight
fc1.0.bias
fc2.0.weight
fc2.0.bias
fc_out.weight
fc_out.bias


In [ ]:
model.modules()

<generator object Module.modules at 0x7fe1ecf5e510>

In [ ]:
list(model.modules())[0] # 0은 전체 

MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Linear(in_features=4, out_features=10, bias=True)
)

In [ ]:
print([m for m in model.modules() if isinstance(m, nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m, nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[-0.1397, -0.0223],
        [-0.5707, -0.6512],
        [ 0.5496, -0.5940]]), Parameter containing:
tensor([[-0.3149,  0.3908, -0.2068],
        [-0.1922, -0.5634,  0.2981],
        [-0.1644,  0.3122, -0.1824],
        [-0.1548, -0.1457, -0.3756]]), Parameter containing:
tensor([[-0.0990,  0.2766, -0.4011,  0.3329],
        [ 0.1677,  0.2721,  0.2828, -0.0207],
        [ 0.1096, -0.3946,  0.0477,  0.2217],
        [ 0.1411,  0.4644,  0.3425,  0.2077],
        [ 0.2591, -0.2632, -0.2729,  0.3236],
        [-0.1293,  0.3663, -0.4023,  0.3493],
        [ 0.1964,  0.3094, -0.3887,  0.4245],
        [-0.3033,  0.3585,  0.1290,  0.3366],
        [ 0.3829,  0.0898,  0.0013, -0.1901],
        [-0.3746, -0.2144, -0.3620, -0.0820]], requires_grad=True)]
[None, None, None]


In [ ]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        nn.init.kaiming_normal_(m.weight)
        nn.init.constant_(m.weight,1)
print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]), Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]), Parameter containing:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)]


In [ ]:
model.children()

<generator object Module.children at 0x7fe1ecf29510>

In [ ]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ), Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ), Linear(in_features=4, out_features=10, bias=True)]

In [ ]:
x=torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.7480, 0.2301, 0.6785],
        [2.4958, 1.9778, 2.4262]])

In [ ]:
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
sub_network(x)

Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)


tensor([[2.2078, 1.3142, 1.3878, 1.0819],
        [7.4511, 6.5575, 6.6310, 6.3252]])

## Sequential vs ModuleList

In [ ]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]
layers1 = nn.Sequential(*layer_list)
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
tensor([[ 0.4349, -0.0303, -0.2643]], grad_fn=<AddmmBackward0>)
tensor([[ 0.4349, -0.0303, -0.2643]], grad_fn=<AddmmBackward0>)


In [ ]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3)))

print(model) # 그냥 리스트로 하면 등록이 안돼있다! 인식을 못함.

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안돼있으면 parameter를 못 찾는다!

tensor([[0.8074, 0.4268, 0.1566]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Linear(in_features=3, out_features=3, bias=True)
  )
)


In [ ]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

block = small_block()
print(block)
model = nn.Sequential(block, block)
print(model)
# model(torch.randn(1),torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안된다!!
# nn.Sequential 이 가지고 있는 forward 함수는 (self,x)로 정의되어서 x,y 두개가 들어가지 못함.

model = nn.ModuleList([block,block])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

small_block(
  (block_x): Linear(in_features=1, out_features=1, bias=True)
  (block_y): Linear(in_features=1, out_features=1, bias=True)
)
Sequential(
  (0): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
  (1): small_block(
    (block_x): Linear(in_features=1, out_features=1, bias=True)
    (block_y): Linear(in_features=1, out_features=1, bias=True)
  )
)
tensor([-0.6400], grad_fn=<AddBackward0>) tensor([-2.8189], grad_fn=<AddBackward0>)
